version: 0.2
#env:
  #variables:
    # key: "value"
    # key: "value"
  #parameter-store:
    # key: "value"
    # key: "value"

phases:
  install:
    commands:
      - echo Installing Node...
      - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - echo Verifying NPM Cache...
      - npm cache verify
      - echo Installing Node Packages...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building Angular For Production...
      - ./node_modules/@angular/cli/bin/ng build --prod
  post_build:
    commands:
      - echo Build completed on `date`
#discard-paths: yes
#base-directory: location
#cache:
#paths:
# - paths
